version: '2.4'

services:
    db:
        image: mdillon/postgis:9.6
        container_name: db  
        restart: always
        env_file: .env
        volumes: 
            - ./data/psql:/var/lib/postgresql/data
            - ./data/backup:/opt
            - /etc/localtime:/etc/localtime:ro   
            - /etc/timezone:/etc/timezone:ro  
        networks: 
            - lan

    dhis:
        image: tomcat:8-jre8
        container_name: dhis
        restart: always
        mem_limit: 3g
        env_file: .env
        volumes:  
            - ./conf/dhis:/opt/dhis2 
            - ./conf/tomcat/webapps:/usr/local/tomcat/webapps
            - ./conf/tomcat/conf:/usr/local/tomcat/conf
            - /etc/localtime:/etc/localtime:ro   
            - /etc/timezone:/etc/timezone:ro  
        ports:
            - $PORT:8080
        networks: 
            - lan  
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        mem_limit: 1g
        # env_file: .env
        volumes:  
            - ./conf/nginx/html:/usr/share/nginx/html
            - /etc/localtime:/etc/localtime:ro   
            - /etc/timezone:/etc/timezone:ro  
        ports:
            - 90:80
        networks: 
            - lan 
                        
networks: 
    lan:
        name: interventions.net
        driver: bridge                       
